default: &default
  adapter: postgresql
  encoding: unicode
  username: fixme
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: cable_test_development

test:
  <<: *default
  database: cable_test_test

production:
  <<: *default
  database: cable_test_production
