default: &default
  adapter: postgresql
  encoding: unicode
  username: fixme
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: my_liege_development

test:
  <<: *default
  database: my_liege_test

production:
  <<: *default
  database: my_liege_production
